[package]
name = "x86_64_linux_hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
lazy_static = "1.4.0"
kernel = { path = "../kernel" }
