[package]
name = "zynqmp_rpu_hello"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pudding-pac    = { version="0.1.3", default-features=false} 
pudding-kernel = { version="0.1.1", default-features=false, features=["pl390"] } 

[build-dependencies]
cc = "1.0.36"
