[package]
name = "hello"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pudding-kernel = "0.1.2"
aligned = "0.4.0"